### ISSUE TITLE
http on config.php even though I defined an https on .env

### ISSUE THREAD

**Issue by AlexDaciuk** [mondediefr/flarum#1]
Hello, I installed your container and after configuring the reverse proxy with nginx and SSL, after installing the forum, I ran into a problem

The forum homepage was blank with only the forums title, using Chrome developer console I saw this

> 'https://foro.lug.fi.uba.ar/' was loaded over HTTPS, but requested an insecure stylesheet 'http://foro.lug.fi.uba.ar/assets/forum-6c6cf9f4.css'. This request has been blocked; the content must be served over HTTPS.

After searching a little on Flarum own forum, I found that you have to [change http for https on the config.php file ](https://discuss.flarum.org/d/3692-ssl-for-flarum)

After changing http for https it works as it should.

The thing is that I explicitly definen a https  FORUM_URL on the .env file for docker compose

It is supposed to put exactly that url on the config.php file?

**Comment by hardware** [comment]
> It is supposed to put exactly that url on the config.php file?

Absolutely, this variable set the **_baseUrl_** parameter in config.yml file and then this value is set in **_config.php_** during flarum installation.

```bash
cat > config.yml <<EOF
[...]
baseUrl: ${FORUM_URL}
EOF
```
`flarum install --file config.yml`

**Comment by AlexDaciuk** [comment]
But it doesn't, at least with the last version of the dockerfile from dockerhub

**Comment by hardware** [comment]
It's because i removed the writeSettings step during flarum installation, try removing this line and restart the container https://github.com/mondediefr/flarum/blob/master/startup#L84

Flarum isn't docker friendly for the moment... I will do some tests this weekend on this issue.

**Comment by hardware** [comment]
I think i found a solution, instead of using `install` command when flarum is already installed, i should use `migrate` command and update manually the config.php file with database params, baseUrl and debug mode.

First installation :

```bash
php flarum install --file config.yml
```

When flarum is already installed :

```bash
php flarum migrate
php flarum cache:clear

# Update config.php file :
if [ -f "config.php" ]; then
  sed -i -e "s|\('debug' =>\) .*|\1 ${DEBUG},|" \
         -e "s|\('url' =>\) .*|\1 ${FORUM_URL},|" config.php
         ...
fi
```

**Sources :**

[php flarum install](https://github.com/flarum/core/blob/685d5f151793544a433d5f027f3dc87e80ec702f/src/Install/Console/InstallCommand.php#L59)
[php flarum migrate](https://github.com/flarum/core/blob/685d5f151793544a433d5f027f3dc87e80ec702f/src/Update/Console/MigrateCommand.php#L39)
[php flarum cache:clear](https://github.com/flarum/core/blob/9bfb797fdc94f2bc1be342e15c89765a70d5fe33/src/Debug/Console/CacheClearCommand.php#L55)

**Comment by AlexDaciuk** [comment]
Sorry for not answering, but I'm having DNS problems with my server so can't test this

I'll be posting when I'm get my DNS going

Cheers

**Comment by AlexDaciuk** [comment]
After pulling the latest image and running the compose with https url declared on .env, doesn't seem to be having any problem with https, closing the issue
